server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://db.hvmsbjcnfsuqrfmexmjj.supabase.co:5432/postgres?currentSchema=mcafe
    username: ${MCAFE_DB_USERNAME}
    password: ${MCAFE_DB_PASSWORD}

  profiles:
    active: ${spring.profiles.default:local}
  mvc:
    path match:
      matching-strategy: ant_path_matcher

database:
  api:
    key: Bearer GeiISm46X8FXbkQmE10iHm6hc2hdtdzJlC05po8DSVNtzF-zOQ
